### ISSUE TITLE
Not working in build: 2021.1_24.5_stable

### ISSUE THREAD

**Issue by lemain** [AiSatan/node_wrangler_octane#17]
Hi there, 
When I try to "add principled texture setup" by using the shortcut. 
Nothing happens and I get the message " Select shader node" even tough I did select the shader node.

When I try to "add texture setup" the projection & transform nodes end up in the wrong input.

Hope to hear from you soon.
Your addon makes working with octane so enjoyable!

Kind regards

**Comment by AiSatan** [comment]
Hi, 
Thanks for letting me know, I will update the addon ASAP and let you know here

**Comment by AiSatan** [comment]
Hi again, I fixed most of the things for build 2021.1_24.5_stable (and for blender 3.0 as well).

Textures setup / control+t / viewer node - should work fine.
But be aware of some possible issues with viewer node, because octane changed shaders output type.
Also, I think some things still can be partly broken/buggy, be free to open another issue here and I will try to fix them as well, 
Thanks

**Comment by lemain** [comment]
Thank you for the quick respond time and for giving me a heads up!

**Comment by AiSatan** [comment]
Totally forgot to add as a release, be free to use this link:

https://github.com/AiSatan/node_wrangler_octane/releases

**Comment by nosyguy** [comment]
@AiSatan thanks soooooooooo much. I spend hours trying to fix the issues after upgrading to the new version. I got it somewhat work but your update is wayyyyyyyyy smoother! You are life saver :)

**Comment by AiSatan** [comment]
@nosyguy Oh, don't be shy to create an issue next time, I'll be happy to help, thanks :)
