### ISSUE TITLE
Grayscale image maps

### ISSUE THREAD

**Issue by Alesino** [AiSatan/node_wrangler_octane#47]
Could you implement grayscale images for the maps that dont need rgb channel? That way it saves alot on computing power.

**Comment by AiSatan** [comment]
Hi, 
Can you add more deatils,
Is it for texure/shader setup? Can you add a picture with node setup you expect to get?
Do you want something like issue #16, with just gamma correction set to 1 for non-color maps or something more?

**Comment by Alesino** [comment]
When you do ctr+shift+T then select all the texture maps to import. So when the images get importated, are the ones that have only black and white channel imported as grayscale images?

![image](https://github.com/AiSatan/node_wrangler_octane/assets/51998659/729c9334-1165-4295-84e2-1a5fb8663d77)
![image](https://github.com/AiSatan/node_wrangler_octane/assets/51998659/5cbeb4b5-c460-4dab-acd8-5b263d6d8f7a)

**Comment by AiSatan** [comment]
I see, 
yes, some of them ('Metallic', 'Roughness', 'Specular', 'Bump') should already use grayscaled, I have this code for it:

`
if sname[0] in ['Metallic', 'Roughness', 'Specular', 'Bump']:
     texture_node = nodes.new(type='OctaneGreyscaleImage')
else:
    texture_node = nodes.new(type='OctaneRGBImage')
`

I can double check, if you think they don't use them for some reason

**Comment by Alesino** [comment]
![image](https://github.com/AiSatan/node_wrangler_octane/assets/51998659/3d33c79e-a534-4f2a-830d-3589bbd80734)
Sweet! I assume that will also work for other short name assigned to the group of lets say specular right?

**Comment by Alesino** [comment]
I just checked and it seems to work! Thanks for the help.

**Comment by AiSatan** [comment]
Great!

Yeah, everything here in 'Metallic', 'Roughness', 'Specular', 'Bump' should be used with grayscale,

Also, if you want to add some maps as grayscale instead of RGB as well, you can ask me, I will add them to latest release.

Or. if you use specific version of the plugin with specific version of octane, you can easily add it just for yourself, it should be super easy

just open my .py file in notepad, find this like:

`if sname[0] in ['Metallic', 'Roughness', 'Specular', 'Bump']:`

and add any of this lines

`
[Displacement,
        ['Albedo color',,
        ['Diffuse color', ,
        ['Albedo', 
        ['Diffuse', 
       ['Medium', 
        ['Metallic', 
        ['Specular', 
        ['Specular map', 
        ['Roughness',
        ['Bump', 
        ['Normal', 
        ]
`

for example if you want to add Normal

`if sname[0] in ['Metallic', 'Roughness', 'Specular', 'Bump', 'Normal']:`

save, remove old plugin install your version, and Normal(or whatever you choosed) will be grayscale as well,
and if not, you know there to find me :)
