### ISSUE TITLE
blender octane 28.7 not working properly

### ISSUE THREAD

**Issue by Jackbrobeep** [AiSatan/node_wrangler_octane#54]
![image](https://github.com/AiSatan/node_wrangler_octane/assets/136829587/33514770-a0af-4390-ae4b-9253aed6c4db)

**Comment by AiSatan** [comment]
Hi, I will take a look and make a fix but it'll out only with next version, sinci it's "mix" feature related with which i having issues right now as well

I will close this issues as soon as fix is up, thanks for letting me know.

**Comment by Jackbrobeep** [comment]
Thank you very much for your reply, I will try it!

AiSatan ***@***.***> 于2024年1月20日周六 12:57写道：

**Comment by Jackbrobeep** [comment]
Thank you. Currently, there is a problem with mixing textures. The version number is octaneblender 28.7.

**Comment by AiSatan** [comment]
Hi,
I'm working on fix for this, it'll be available soon, thanks!

**Comment by Jackbrobeep** [comment]
The blender octane version is iterating too fast. It has been updated to v28.9 now. I think it is better to wait until it is more stable before adapting. The current version still has many small problems.

**Comment by piggywithmonster** [comment]
> Hi, I will take a look and make a fix but it'll out only with next version, sinci it's "mix" feature related with which i having issues right now as well
> 
> I will close this issues as soon as fix is up, thanks for letting me know.

Is this bug fixed yet?

**Comment by AiSatan** [comment]
You can try this version and let me know if it works for you, thanks!

[node_wrangler_octane.zip](https://github.com/AiSatan/node_wrangler_octane/files/14382262/node_wrangler_octane.zip)

Please just use this zip file as an addon, DO NOT unzip

**Comment by piggywithmonster** [comment]
> You can try this version and let me know if it works for you, thanks!
> 
> [node_wrangler_octane.zip](https://github.com/AiSatan/node_wrangler_octane/files/14382262/node_wrangler_octane.zip)
> 
> Please just use this zip file as an addon, DO NOT unzip

Thank you very much, mix material can be used normally now. but,the mix material is still not working.
I have a suggestion，I think it's possible to generate composite node,because this is more powerful.

**Comment by piggywithmonster** [comment]
> You can try this version and let me know if it works for you, thanks!
> 
> [node_wrangler_octane.zip](https://github.com/AiSatan/node_wrangler_octane/files/14382262/node_wrangler_octane.zip)
> 
> Please just use this zip file as an addon, DO NOT unzip

Thank you very much, mix texture can be used normally now. but,the mix material is still not working.
I have a suggestion，I think it's possible to generate composite node,because this is more powerful.

**Comment by piggywithmonster** [comment]
Thank you very much, mix texture can be used normally now. but,the mix material is still not working.
I have a suggestion，I think it's possible to generate composite node,because this is more powerful.
![Snipaste_2024-02-24_15-28-57](https://github.com/AiSatan/node_wrangler_octane/assets/20817622/bf701ade-e1ee-45d5-a778-7f6f6ba63f1c)
![Snipaste_2024-02-24_15-29-57](https://github.com/AiSatan/node_wrangler_octane/assets/20817622/09c573f3-044b-480d-9d1e-35c0b9da5c09)
![Snipaste_2024-02-24_15-31-17](https://github.com/AiSatan/node_wrangler_octane/assets/20817622/a5fa23f4-9f24-4e9d-8312-9e1136724976)

**Comment by AiSatan** [comment]
Hi, 

I fixed mix nodes as well, bubut I'm using mix material (and mix texute) instead of composite node, since it doesn't have mix value parametr and I already implemented with mix materials node long time ago, I think this change can brake something for people aleady using it

Please give a try to latest release here, and thank you! :)

https://github.com/AiSatan/node_wrangler_octane/releases

**Comment by piggywithmonster** [comment]
Thanks again.
